apiVersion: batch/v1
kind: Job
metadata:
  generateName: kuber-workflow-approver
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: ubuntu
        envFrom:
        - secretRef:
            name: kuber-secret
        command:
          - "echo secret:$SECRET"
          - "curl"
          - "-X"
          - "POST"
          - "-H"
          - "Authorization: Bearer $SECRET"
          - "-H"
          - "Content-Type: application/json"
          - "https://api.github.com/repos/PricerAB/Kuber/actions/runs/3593891925/pending_deployments"
          - "-d"
          - "{\"environment_ids\":[743920904],\"state\":\"approved\",\"comment\":\"Ship it!\"}"
      restartPolicy: Never
  backoffLimit: 2