apiVersion: batch/v1
kind: Job
metadata:
  generateName: kuber-workflow-approver
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: workflow-approver
        image: curlimages/curl
        envFrom:
        - secretRef:
            name: kuber-secret
        command: ["curl"]
        args: ["www.example.com"]
      restartPolicy: Never
  backoffLimit: 2

  # "-v -X POST -H \"Accept: application/vnd.github+json\" -H \"Authorization: Bearer $API_TOKEN\" https://api.github.com/repos/ekk020/Kuber/actions/runs/3593891925/pending_deployments -d '{\"environment_ids\":[743920904],\"state\":\"approved\",\"comment\":\"Ship it!\"}'"