apiVersion: batch/v1
kind: Job
metadata:
  generateName: kuber-workflow-approver
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: workflow-approver
        image: curlimages/curl
        envFrom:
        - secretRef:
            name: kuber-secret
        command: ["/bin/echo"]
        args: ["$(API_TOKEN)"]
      restartPolicy: Never
  backoffLimit: 2