apiVersion: v1
kind: Service

metadata:
  labels:
    service: kuber-service
    app: kuber-service
  name: kuber-service
  namespace: default

spec:
  type: NodePort
  selector:
    app: kuber
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 7878