apiVersion: batch/v1
kind: Job
metadata:
  generateName: kuber-workflow-approver
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "-H"
          - "Authorization: Bearer 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"
          - "-H"
          - "Content-Type: application/json"
          - "https://api.github.com/repos/PricerAB/Kuber/actions/runs/3593891925/pending_deployments"
          - "-d"
          - "{\"environment_ids\":[743920904],\"state\":\"approved\",\"comment\":\"Ship it!\"}"
      restartPolicy: Never
  backoffLimit: 2