apiVersion: batch/v1
kind: Job
metadata:
  generateName: kuber-workflow-approver
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: ubuntu
        envFrom:
        - secretRef:
            name: kuber-secret
        command:
          - "echo"
          - "secret:$API_TOKEN"
      restartPolicy: Never
  backoffLimit: 2