apiVersion: v1
kind: Service

metadata:
  labels:
    service: kuber-service
    app: kuber-service
  name: kuber-service
  namespace: default

spec:
  selector:
    app: kuber
  ports:
  - name: http
    port: 7878
    protocol: TCP
    targetPort: 7878