apiVersion: batch/v1
kind: Job
metadata:
  generateName: kuber-workflow-approver
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: workflow-approver
        image: curlimages/curl
        envFrom:
        - secretRef:
            name: kuber-secret
        command: ["/bin/curl"]
        args: ["-v -X POST -H \"Accept: application/vnd.github+json\" -H \"Authorization: Bearer $API_TOKEN\" https://api.github.com/repos/ekk020/awdad/actions/runs/awdadwa/pending_deployments -d '{\"environment_ids\":[awdwad],\"state\":\"approved\",\"comment\":\"Ship it!\"}'"]
      restartPolicy: Never
  backoffLimit: 2