name: Render kubernetes manifests

on:
  push: 
    branches: [ main ]
    paths: 
      - 'raw-configs/*/*'
      - .github/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: parse commit
        id: parse
        run: | 
          commit=$(echo "${{ github.event.head_commit.message }}" | tail -3)
          echo $commit
          for word in $commit; do
            IFS=':' read -r key val <<< "$word"
            if [[ "$key" == "runid" ]]; then
              echo "run_id=$val" >> $GITHUB_OUTPUT
            elif [[ "$key" == "repo" ]]; then
              echo "repo=$val" >> $GITHUB_OUTPUT
            elif [[ "$key" == "envid" ]]; then
              echo "env_id=$val" >> $GITHUB_OUTPUT
            fi
          done
        shell: bash
      - name: generate hook
        run: |
          echo r:${{ steps.parse.outputs.repo }} i:${{ steps.parse.outputs.run_id }} env:${{ steps.parse.outputs.envid }}
          python3 kuber-hook.py ${{ secrets.API_GITHUB_TOKEN }} ${{ steps.parse.outputs.repo }} ${{ steps.parse.outputs.run_id }} ${{ steps.parse.outputs.envid }}
      - name: Run render script
        run: ./render.sh
      - name: Commit if changes
        run: |
          git --version
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git commit -m "Workflow commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}